services:
  money_roll_db:
    image: postgres:latest
    container_name: money_roll_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money-roll-db
    ports:
      - "5432:5432"

  money_roll_test_db:
    image: postgres:latest
    container_name: money_roll_test_db_postgres
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: money-roll-test-db
    ports:
      - "5433:5432"